---
title: "rumble.nyc"
theme: default

connectivityCheck: true
footer: false

links:
  - name: Homepage
    url: https://irumble.com
  - name: Beats with Benji
    url: https://irumble.com/beatswithbenji

services:
  - name: Socials
    items:
      - name: Twitter
        url: https://twitter.com/therumbler
        target: "_blank"
      - name: Soundcloud
        url: https://soundcloud.com/therumbler
        target: "_blank"
      - name: Instagram
        url: https://instagram.com/therumbler
        target: "_blank"

colors:
  light:
    highlight-primary: "#2E3440"
    highlight-secondary: "#2E3440"
    highlight-hover: "#2E3440"
    background: "#2E3440"
    card-background: "#2E3440"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"

  dark:
    highlight-primary: "#2E3440"
    highlight-secondary: "#2E3440"
    highlight-hover: "#2E3440"
    background: "#2E3440"
    card-background: "#2E3440"
    text: "#81A1C1"
    text-header: "#81A1C1"
    text-title: "#D8DEE9"
    text-subtitle: "#ECEFF4"
    status-offline: "#BF616A"
    status-online: "#A3BE8C"
